---
- name: Wait until mysqld starts
  pause: 
    seconds: 40
- name: Set and start replication
  command: >
    docker exec {{ item }} bash -c "MYSQL_PWD=; mysql -uroot -e \"change master to master_host='mysql1', master_user='root', master_log_file='mysql-bin.000001', master_log_pos = 4; start slave\""
  with_sequence: start={{0 if servers|int == 1 else servers }} end="{{ servers }}" format=mysql%01x